/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * mnemos-zero API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

export type GetApiHealth200 = {
  ok: boolean;
};

export type GetApiMessages200Item = {
  id: number;
  text: string;
  createdAt: string;
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const getApiHealth = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiHealth200>> => {
  return axios.get(`/api/health`, options);
};

export const getGetApiHealthQueryKey = () => {
  return [`/api/health`] as const;
};

export const getGetApiHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealth>>> = ({ signal }) =>
    getApiHealth({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiHealth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealth>>>;
export type GetApiHealthQueryError = AxiosError<unknown>;

export function useGetApiHealth<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiHealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiMessages = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiMessages200Item[]>> => {
  return axios.get(`/api/messages`, options);
};

export const getGetApiMessagesQueryKey = () => {
  return [`/api/messages`] as const;
};

export const getGetApiMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMessagesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMessages>>> = ({ signal }) =>
    getApiMessages({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMessages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMessages>>>;
export type GetApiMessagesQueryError = AxiosError<unknown>;

export function useGetApiMessages<
  TData = Awaited<ReturnType<typeof getApiMessages>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getApiMessages>>, TError, TData>;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiMessagesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
